spring:
  datasource:
      url: jdbc:mysql://localhost:3306/saw_auth?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 100
      minIdle: 8
      initialSize: 30
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxWait: 60000
      #check connection
      timeBetweenEvictionRunsMillis :  60000
      minEvictableIdleTimeMillis :  300000
      validationQuery :  SELECT 'x'
      testWhileIdle :  true
      testOnBorrow :  false
      testOnReturn :  false
      poolPreparedStatements :  true
      maxPoolPreparedStatementPerConnectionSize :  20
      filters :  stat